# Generated by Django 2.0.2 on 2020-11-30 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_created_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
