# Generated by Django 2.0.2 on 2020-11-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_article_article_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_dislikes',
        ),
    ]
